services:
  mysql:
    image: mysql:8.4
    container_name: sneaker_mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sneaker_flash
      MYSQL_USER: cot
      MYSQL_PASSWORD: qB645522153
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - sneaker-net
    command: --mysql-native-password=ON

  redis:
    image: redis:8.2
    container_name: sneaker_redis
    ports:
      - "16379:6379"
    command: redis-server --requirepass 123456 --appendonly yes
    volumes:
      - redis:/data
    networks:
      - sneaker-net
  
  kafka:
    image: apache/kafka:4.1.1
    container_name: sneaker_kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft 核心配置
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # 监听器配置
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka:/bitnami/kafka
    networks:
      - sneaker-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: sneaker_kafka_ui
    ports:
      - "8080:8080"
    environment:
      - KAFKACLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - sneaker-net

networks:
  sneaker-net:
    driver: bridge
  
volumes:
  kafka:
  mysql:
  redis: